"use client";

import { useState } from "react";
import { ArrowUpRight, Check, GitBranch, Link2, MessageCircle, SearchX, Tags, UsersRound } from "lucide-react";
import { origins } from "@/data/operationsMock";
import { Button } from "@/components/ui/Button";
import { Drawer } from "@/components/ui/Drawer";
import { Modal } from "@/components/ui/Modal";
import { ModalChoice, ModalSelect } from "@/components/ui/ModalField";
import { PageHeader, SearchField, StatePanel, TableCell, TableHeaderCell, TableHead, TableSurface } from "@/components/ui/Week1Primitives";

export function ContactOriginsPage() {
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<typeof origins[number] | null>(null);
  const [rulesOpen, setRulesOpen] = useState(false);
  const filtered = origins.filter((origin) => `${origin.ticket} ${origin.contact} ${origin.originContact} ${origin.whatsapp}`.toLowerCase().includes(search.toLowerCase()));
  return <div><PageHeader eyebrow="Pacientes / Relacionamentos" title="Origens de contato" description="Entenda de onde cada contato chegou e preserve a origem no contexto do atendimento." action={<Button variant="secondary" onClick={() => setRulesOpen(true)}><GitBranch className="size-4" />Ver regras de origem</Button>} /><div className="mb-4 flex flex-col gap-2 rounded-[24px] border border-clinical-border/[0.14] bg-clinical-surface/70 p-2.5 sm:flex-row sm:items-center"><SearchField value={search} onChange={setSearch} placeholder="Buscar ticket, contato ou origem" /><span className="flex shrink-0 items-center gap-2 rounded-2xl bg-clinical-blue/[0.07] px-3 py-2 text-xs font-bold text-clinical-blueText"><Link2 className="size-4" />{filtered.length} relações</span></div>{filtered.length === 0 ? <StatePanel icon={SearchX} title="Nenhum relacionamento encontrado" description="Não encontramos registros com esse termo." action={<Button size="sm" variant="secondary" onClick={() => setSearch("")}>Limpar busca</Button>} /> : <TableSurface caption="Origens de contato"><TableHead><TableHeaderCell>Ticket</TableHeaderCell><TableHeaderCell>Contato</TableHeaderCell><TableHeaderCell>Contato de origem</TableHeaderCell><TableHeaderCell>WhatsApp</TableHeaderCell><TableHeaderCell>Data de criação</TableHeaderCell><TableHeaderCell>Ações</TableHeaderCell></TableHead><tbody className="divide-y divide-clinical-border/[0.10]">{filtered.map((origin) => <tr key={origin.id} className="animate-list-in transition hover:bg-clinical-blue/[0.035]"><TableCell><span className="font-extrabold text-clinical-blueText">{origin.ticket}</span></TableCell><TableCell><span className="font-extrabold text-clinical-dark">{origin.contact}</span></TableCell><TableCell>{origin.originContact}</TableCell><TableCell>{origin.whatsapp}</TableCell><TableCell>{origin.createdAt}</TableCell><TableCell><button type="button" onClick={() => setSelected(origin)} className="inline-flex items-center gap-1.5 font-extrabold text-clinical-blueText hover:underline">Ver relação <ArrowUpRight className="size-4" /></button></TableCell></tr>)}</tbody></TableSurface>}
    <Drawer open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.ticket ?? "Relação"} description="Origem associada ao contato.">{selected ? <dl className="space-y-5"><div><dt className="text-xs font-extrabold uppercase tracking-wider text-clinical-muted">Contato</dt><dd className="mt-1 text-sm font-bold text-clinical-dark">{selected.contact}</dd></div><div><dt className="text-xs font-extrabold uppercase tracking-wider text-clinical-muted">Origem</dt><dd className="mt-1 text-sm font-bold text-clinical-dark">{selected.originContact}</dd></div><div><dt className="text-xs font-extrabold uppercase tracking-wider text-clinical-muted">Criado em</dt><dd className="mt-1 text-sm font-bold text-clinical-dark">{selected.createdAt}</dd></div></dl> : null}</Drawer>
    <Modal open={rulesOpen} onClose={() => setRulesOpen(false)} title="Regras de origem" eyebrow="Relacionamentos" description="A origem acompanha o contato para manter o histórico de aquisição e atendimento." icon={GitBranch} className="max-w-xl"><div className="space-y-3"><ModalChoice label="Campanhas e anúncios" description="Atribui campanhas identificadas no primeiro contato." icon={Tags} active={true} onClick={() => undefined} /><ModalChoice label="Canais de conversa" description="Reconhece WhatsApp, Instagram e outros canais conectados." icon={MessageCircle} active={false} onClick={() => undefined} /><ModalChoice label="Indicações" description="Mantém a pessoa ou equipe que originou a relação." icon={UsersRound} active={false} onClick={() => undefined} /><ModalSelect label="Prioridade de atribuição" icon={Link2} defaultValue="Primeiro ponto de contato"><option>Primeiro ponto de contato</option><option>Última interação</option><option>Origem manual da equipe</option></ModalSelect><div className="flex items-center justify-between rounded-2xl bg-clinical-blue/[0.06] p-3 text-sm font-semibold text-clinical-slate"><span className="flex items-center gap-2"><Check className="size-4 text-clinical-green" />Regras prontas para conectar</span><Button size="sm" onClick={() => setRulesOpen(false)}>Fechar</Button></div></div></Modal>
  </div>;
}
