"use client";

import { useMemo, useState } from "react";
import { BarChart3, Check, ClipboardList, Download, FileText, Filter, SearchX, SlidersHorizontal } from "lucide-react";
import { protocols } from "@/data/operationsMock";
import { Button } from "@/components/ui/Button";
import { Drawer } from "@/components/ui/Drawer";
import { Modal } from "@/components/ui/Modal";
import { ModalChoice, ModalSelect } from "@/components/ui/ModalField";
import { FilterSelect, PageHeader, SearchField, StatePanel, StatusBadge, TableCell, TableHeaderCell, TableHead, TableSurface } from "@/components/ui/Week1Primitives";

export function ProtocolsPage() {
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("Todos");
  const [sector, setSector] = useState("Todos");
  const [selected, setSelected] = useState<typeof protocols[number] | null>(null);
  const [modal, setModal] = useState<"filters" | "export" | null>(null);
  const filtered = useMemo(() => protocols.filter((protocol) => (filter === "Todos" || protocol.status === filter) && (sector === "Todos" || protocol.sector === sector) && `${protocol.id} ${protocol.client} ${protocol.user} ${protocol.sector} ${protocol.queue}`.toLowerCase().includes(search.toLowerCase())), [filter, search, sector]);

  return <div><PageHeader eyebrow="Pacientes / Histórico" title="Protocolos" description="Consulte protocolos, responsáveis e relatórios da jornada de cada paciente." action={<Button variant="secondary" onClick={() => setModal("export")}><Download className="size-4" />Exportar consulta</Button>} /><div className="mb-4 flex flex-col gap-2 rounded-[24px] border border-clinical-border/[0.14] bg-clinical-surface/70 p-2.5 sm:flex-row sm:items-center"><SearchField value={search} onChange={setSearch} placeholder="Buscar por nome, telefone ou protocolo" /><div className="flex shrink-0 gap-2"><FilterSelect label="Status" value={filter} onChange={setFilter} options={["Todos", "Concluído", "Em andamento", "Aguardando"]} /><Button variant="secondary" size="sm" onClick={() => setModal("filters")}><SlidersHorizontal className="size-4" />Filtros</Button></div></div>{filtered.length === 0 ? <StatePanel icon={SearchX} title="Nenhum protocolo encontrado" description="Ajuste a busca ou selecione outro status." action={<Button size="sm" variant="secondary" onClick={() => { setSearch(""); setFilter("Todos"); setSector("Todos"); }}>Limpar filtros</Button>} /> : <TableSurface caption="Lista de protocolos"><TableHead><TableHeaderCell>Nº protocolo</TableHeaderCell><TableHeaderCell>Cliente</TableHeaderCell><TableHeaderCell>Usuário</TableHeaderCell><TableHeaderCell>Setor</TableHeaderCell><TableHeaderCell>Fila</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell><TableHeaderCell>Data</TableHeaderCell><TableHeaderCell>Relatório</TableHeaderCell></TableHead><tbody className="divide-y divide-clinical-border/[0.10]">{filtered.map((protocol) => <tr key={protocol.id} className="animate-list-in transition hover:bg-clinical-blue/[0.035]"><TableCell><span className="font-extrabold text-clinical-blueText">{protocol.id}</span></TableCell><TableCell><span className="font-extrabold text-clinical-dark">{protocol.client}</span></TableCell><TableCell>{protocol.user}</TableCell><TableCell>{protocol.sector}</TableCell><TableCell>{protocol.queue}</TableCell><TableCell><StatusBadge label={protocol.status} tone={protocol.status === "Concluído" ? "green" : protocol.status === "Aguardando" ? "orange" : "blue"} /></TableCell><TableCell>{protocol.date}</TableCell><TableCell><button type="button" onClick={() => setSelected(protocol)} className="inline-flex items-center gap-1.5 font-extrabold text-clinical-blueText hover:underline"><FileText className="size-4" />{protocol.report}</button></TableCell></tr>)}</tbody></TableSurface>}
    <Drawer open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.id ?? "Relatório"} description="Resumo do protocolo e próximos passos.">{selected ? <div><div className="rounded-2xl bg-clinical-blue/[0.07] p-4"><p className="text-sm font-extrabold text-clinical-dark">{selected.client}</p><p className="mt-1 text-xs font-semibold text-clinical-muted">{selected.sector} · {selected.queue} · {selected.date}</p></div><dl className="mt-7 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs font-extrabold uppercase tracking-wider text-clinical-muted">Responsável</dt><dd className="mt-1 text-sm font-bold text-clinical-dark">{selected.user}</dd></div><div><dt className="text-xs font-extrabold uppercase tracking-wider text-clinical-muted">Status</dt><dd className="mt-1"><StatusBadge label={selected.status} tone="green" /></dd></div></dl><div className="mt-7 rounded-2xl border border-clinical-border/[0.12] p-4 text-sm leading-6 text-clinical-slate">O relatório será conectado ao histórico clínico quando a API estiver disponível. Nesta versão, o painel organiza a consulta e a revisão.</div></div> : null}</Drawer>
    <Modal open={modal === "filters"} onClose={() => setModal(null)} title="Filtros de protocolos" eyebrow="Refine a consulta" description="Combine status, setor e fila para reduzir a lista sem perder o contexto." icon={Filter} className="max-w-xl"><div className="space-y-4"><ModalSelect label="Status do protocolo" icon={ClipboardList} value={filter} onChange={(event) => setFilter(event.target.value)}><option>Todos</option><option>Concluído</option><option>Em andamento</option><option>Aguardando</option></ModalSelect><ModalSelect label="Setor responsável" icon={BarChart3} value={sector} onChange={(event) => setSector(event.target.value)}><option>Todos</option><option>Cardiologia</option><option>Recepção</option><option>Exames</option><option>Ortopedia</option></ModalSelect><div className="flex items-center justify-between rounded-2xl bg-clinical-blue/[0.06] p-3 text-sm font-bold text-clinical-blueText"><span>{filtered.length} protocolo(s) na visão</span><button type="button" onClick={() => { setFilter("Todos"); setSector("Todos"); }} className="text-xs underline">Limpar critérios</button></div><div className="flex justify-end"><Button onClick={() => setModal(null)}><Check className="size-4" />Aplicar filtros</Button></div></div></Modal>
    <Modal open={modal === "export"} onClose={() => setModal(null)} title="Exportar consulta" eyebrow="Protocolos" description="Leve a visão atual para uma análise ou revisão externa." icon={Download} className="max-w-xl"><div className="grid gap-3 sm:grid-cols-2"><ModalChoice label="CSV da consulta" description={`${filtered.length} registros com as colunas da tabela.`} icon={Download} active={false} onClick={() => setModal(null)} /><ModalChoice label="Relatório PDF" description="Resumo visual para compartilhar com a equipe." icon={FileText} active={false} onClick={() => setModal(null)} /><ModalChoice label="Dados completos" description="Inclui filtros, responsáveis e status." icon={BarChart3} active={false} onClick={() => setModal(null)} /><ModalChoice label="Copiar link da visão" description="Prepara um link com os critérios atuais." icon={SlidersHorizontal} active={false} onClick={() => setModal(null)} /></div><div className="mt-5 rounded-2xl border border-clinical-green/20 bg-clinical-green/[0.07] p-3 text-sm font-semibold leading-5 text-clinical-slate">A exportação é simulada localmente nesta Semana 1. O modal preserva o fluxo pronto para o serviço real.</div></Modal>
  </div>;
}
